### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by ctoffanin** [YuriDevAT/sos-animals#23]
Hi Julia.
The idea for this project is pretty cool!
Do you plan to go on with it in the future, or was it just for the hackathon?

**Comment by YuriDevAT** [comment]
Hey @ctoffanin. Thank you for your comment and interest. Actually, I do plan on going on with this project pretty soon.

**Comment by ctoffanin** [comment]
That's good to hear! I'd love to help you if you need any (based on my skills, of course).
Glad the project is not left for dead!
Thank you for your reply, and you can close the issue if you want.
Cheers.
